### ISSUE TITLE
Can't get Controls to hide/not show with Player

### ISSUE THREAD

**Issue by knawwxbackme** [moonstar-x/react-twitch-embed#12]
Hey there! Great repo by the way. I'm having some trouble getting the Twitch Player Controls to hide/not show with the Player. Can you let me know how you do it for them not to show? People have said there's a way like with a Controls prop. I would really appreciate any help!

**Comment by moonstar-x** [comment]
Hey there, you're right, there is a way to hide the controls, however I did not implement because this information was not available from the [Documentation for the Player Embed API](https://dev.twitch.tv/docs/embed/video-and-clips#interactive-frames-for-live-streams-and-vods). I just tried adding a control prop and it does hide the controls for online live streams and videos being played from the `TwitchPlayer` component. However, if the live stream is not online, the offline player image will not show up and only a black screen will appear. Also, when videos are loading, the screen will go black too. The player will still capture keyboard events (i.e space will still pause the player).

In any case, I'm going to update `TwitchPlayer` component to accept a `hideControls` prop so this becomes possible.

**Comment by knawwxbackme** [comment]
Thanks so much! When you do could you add little documentation for it and let me know whenever you update it?

**Comment by moonstar-x** [comment]
Sure, I should have it ready in just a minute :)

**Comment by moonstar-x** [comment]
I just updated it in #14, try to update your package on your project. The README has also been updated, just add the `hideControls` prop to your `TwitchPlayer` component and it should hide the controls. Let me know if it works so I can close this issue!

**Comment by knawwxbackme** [comment]
I've never had someone respond so quickly to an issue. Thanks so much!

**Comment by moonstar-x** [comment]
Alright then! Thanks for posting this issue, I didn't know this was possible until now.

I'm closing the issue then, if you need something else don't hesitate to create another issue.
