### ISSUE TITLE
TypeError: Cannot read property 'setChannel' of undefined

### ISSUE THREAD

**Issue by johndevor** [moonstar-x/react-twitch-embed#26]
![CleanShot 2020-09-28 at 17 04 41](https://user-images.githubusercontent.com/75827/94485992-c53c5400-01ac-11eb-9255-e9348c6c2199.png)

**Comment by johndevor** [comment]
When changing the channel

**Comment by moonstar-x** [comment]
Hey there, quick questions:
1. Are you using any sort of server side rendering or just plain React?
2. If you open the Network inspector of your browser, do you see a request to the following URL: `https://player.twitch.tv/js/embed/v1.js`?
3. I see the trace shows the error in a file that is not inside node_modules, Are you trying to use the source code directly or are you using the package from npm? (which is packed and transpiled to work in the browser since it's written in ES6 and browser js does not recognize the `import` statement which is probably what's causing this issue).

**Comment by johndevor** [comment]
1. It's client-side rendered, however I'm rendering the embed inside a web component. And to be clear, it does work, just can't change the channel. I made a hacky workaround: 

```
const reloadChannel = () => {
    if (!channelReloaded) {
      setTimeout(() => {
        setChannelReloaded(true);
      }, 250);
    }
  };
```

2. I see this, looks like a call to https://gql.twitch.tv/gql but I'm not seeing v1.js

![CleanShot 2020-09-29 at 12 54 34](https://user-images.githubusercontent.com/75827/94589189-f5d6c900-0252-11eb-9589-211b5466b4a2.png)

3. I'm using yarn @ `"react-twitch-embed": "^2.1.0"`

**Comment by moonstar-x** [comment]
I'm not very familiar with web components. Does this mean that you're not using React to render your page?
I'm a bit surprised that the embed even shows up if you have no requests to `https://embed.twitch.tv/embed/v1.js` since the component downloads this script and adds it to your HTML body the first time that `componentDidUpdate()` is called.

![image](https://user-images.githubusercontent.com/14969195/94590377-32eb8d00-024c-11eb-9a33-ec77250e43f5.png)

How exactly does your project work? Like I said I'm not very familiar with web components. If I had to guess, I would say that inside `TwitchEmbed`, `_createEmbed()` is not being called since that method is the one that will set the `this.player` object once the embed is ready.

**Comment by moonstar-x** [comment]
I just realized why this is happening, you're updating the channel prop way too soon (before the player is initialized to be specific). I'll have to refactor the `componentDidUpdate` method to avoid this error.

**Comment by johndevor** [comment]
Ah, ok. Thanks for looking into this! That makes sense.

**Comment by moonstar-x** [comment]
Hi there, sorry for the long hiatus.

I'm gonna close this issue due to inactivity. However, I have just updated this package to version `3.0.1` with #37.

Any reference to `window` or `document` have been moved to `useEffect()` which should be executed in the client for SSR apps.

If you feel this was a mistake, feel free to re-open this issue.

Thanks!
