### ISSUE TITLE
Add new picture-in-picture attribute

### ISSUE THREAD

**Issue by guilherssousa** [moonstar-x/react-twitch-embed#30]
Web browsers started using native picture-in-picture modes for videos and images, and they're automatically set. Per the spec at [W3C Editors Draft](https://w3c.github.io/picture-in-picture/#disable-pip), a new attribute called _disablePictureInPicture_ is ready to be used in order to disable picture-in-picture frames.

But, your component is filtered for predefined attributes that are passed to the final embed, so it's hard to implement a direct solution for the problem, is that simple to add it? Can I do a fork and do it myself? I'm not used to class components.

**Comment by moonstar-x** [comment]
Hey there, the prop filtering you mention actually filters out the props that are specified in the propTypes, so if you were to add something like a `disablePictureInPicture` prop, it would go straight to the `div` that contains the embed.

I'm gonna look a bit into this, I don't have my computer next to me but if you were to pass that prop it should go to the `div`.

If it doesn't work then it may be due to the fact that Twitch Embed scripts actually inject the iframe into a parent component so you don't get direct access to the iframe component. I'm gonna check if the embed documentation talks about disabling picture-in-picture or if there's a way to add props directly to the iframe.

**Comment by guilherssousa** [comment]
Oh, thanks :)

**Comment by moonstar-x** [comment]
I was looking into the Twitch Embed documentation to see if it would accept an attribute like this and I couldn't find anything.

Moreover, I actually couldn't find a way to have the Twitch player work in Picture-in-Picture mode. Have you actually gotten this to happen? I've tried right clicking the player and see if there was something in the settings cog menu but nothing suggests the ability to use it in Picture-in-Picture.

Are you by any chance using React Native?

**Comment by guilherssousa** [comment]
No, probably I explained it wrong, I don't want to enable picture-in-picture mode, I want to disable it

By default on recent browsers like Chrome, when you hover the embed, it shows a pop-up to enable, I want to disable this button

I'm using React JS :)

**Comment by moonstar-x** [comment]
Ah no, don't worry you did explain yourself correctly. The thing I tried to say is that if you want to disable something you must first enable it and I couln't find a way to enable picture-in-picture.

As far as I{m concerned, I'm using the latest Chrome version and I still don't get the pop-up you mention. I can only enter picture-in-picture on things like YouTube.

I read a bit the spec that you sent me and I'm seeing that the attribute you mention is for `video` elements and since the embeds are basically `iframe`s, I don't think I would have access to the underlying `video` element, especially since it would modify the document from another domain which I'm sure as hell is not possible.

I think the best bet right now would be to wait and see if Twitch supports these attributes themselves and exposes them through their embeds API.

**Comment by guilherssousa** [comment]
Oh, thank you :)
