### ISSUE TITLE
Add typings.

### ISSUE THREAD

**Issue by ZeroPointGaming** [moonstar-x/react-twitch-embed#33]
Error: Could not find a declaration file for module 'react-twitch-embed'. 'c:/Users/ClassifiedUser/ClassifiedProject/node_modules/react-twitch-embed/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-twitch-embed` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-twitch-embed';
  
  Tried both import and namespace imports
import * as reactTwitchEmbed from 'react-twitch-embed';
import { TwitchEmbed, TwitchChat, TwitchClip, TwitchPlayer } from 'react-twitch-embed';

Neither of which will work in gatsby-react.

**Comment by moonstar-x** [comment]
Are you using typescript by any chance?

I haven't created typings for the package, (which I should've :p). In any case, if you create a `*.d.ts` file with the following content:

```ts
declare module 'react-twitch-embed';
```

The error should go away. Obviously, this means you won't have types for the components (although props should still be autocompleted because of propTypes).

This is obviously not a solution but a workaround. I'm gonna have to add the typings one of these days.

**Comment by ZeroPointGaming** [comment]
Gotcha

**Comment by moonstar-x** [comment]
Hi there, sorry for the long hiatus.

This has been added in version `3.0.1` with #37.
